const yahooData = {
  a: [
    "a little bit of milk breast",
    "after making savage love to a woman she curled up close to me purring",
    "are questions more threatening than statements",
    "are these gay words for a guy to say",
    "arent public records free for anyone to look at",
    "and one more rewrite i really appreciate",
    "another poem i'm sure everyone's sick of",
    "anyone same with me",
    "any way to get rid of an advanced toe nail fungus",
    "a few short jokes how did the aliens hurt",
  ],
  b: [
    "bad breath in children",
    "best ways of quitting cannabis forever",
    "big brother who thinks amanda wud b much better with liam",
    "bout how much would a shitzu costs in montreal",
  ],
  c: [
    "can you catch herpes from a toilet seat",
    "can a week old pupy eat the barf",
    "confucius say hold faithfullness and sincerity as first principles",
    "can yo get a sore throat from giving oral sex",
    "can yo get a sore throat from giving oral sex",
    "could this new flu outbreak be sars",
    "can any one let me know",
    "can you write me a cowboy poem",
    "can anyone help in understanding an aries",
    "coke teeth",
    "carpal corpal tunnel syndrome",
    "Clubpenguin help?",
  ],
  d: [
    "do your curtains match your drapes",
    "do buns look good with people with glasses",
    "do you like your mom",
    "does anyone know how much tongue tie surgery costs",
    "does anyone else have a problem",
    "does your dog eat",
    "do you know where and how much",
    "do u find it really hard to talk to someone when they're makeup is terrible",
    "does anyone know the economic and social role of men",
    "does anyone remember",
    "ddt safe or dangerous for developing nations",
    "do you like these poems should i die",
  ],
  e: [
    "ever heard of anoyone dying from a meningitis vaccine",
    "extreme dizziness what is causing this",
    "edward norton or christian bale",
  ],
  f: ["for the past wks fingers on my lefthand have been numb"],
  g: [
    "good face wash for guys",
    "gemini girls why",
    "going from inseperable to nothing",
  ],
  h: [
    "has my cat lost her mind what should i do",
    "hiccups i have them",
    "how can i bellydance like shakira",
    "how do you escape from somebody when the enemy is yourself talk to a mirror",
    "how safety is the gold gate bridge",
    "how can you stop bleeding",
    "help please today",
    "high school help plz",
  ],
  i: [
    "i'm looking for my father who i've never seen",
    "is love just a conquest",
    "i think i developed a cocaine addiction help",
    "i'm a capricorn so how come",
    "invisalign does invisalign",
    "i may have stepped on a crack in the pavement today is that a valid excuse for not going to work tomorrow",
    "is this herpes how did he get it",
    "is anyone dead",
    "is breakfast at tiffany's a good movie",
  ],
  j: ["just like i said.... i dont know what to do", "Japanese band in the movie Kill Bill Vol. 1?"],
  k: ["klepto??????"],
  l: ["Ladies, what do you think about 'hobosexual' men?"],
  m: [
    "my mom's foot is numb it's been numb for a full day",
    "most hated sign of the zodiac",
    "my eyelid won't stop twitching",
    "my feces is a bright blue",
    "My friends did a luigi board.. and it mentioned me! PLEAS HELP!?",
  ],
  n: ["no not prostitution", "need help finding a phsycic"],
  o: [
    "on average how much are da vinci veneers",
    "only and the first person ive slept with i contracted hpv",
  ],
  p: [
    "please how do you clean yourself",
    "poltergeist question",
    "prank im looking for a good prank",
    "Placental abruption?",
  ],
  q: ["questions for mothers living"],
  r: ["relationship between adolf hitler henry ford"],
  s: [
    "someone help me please",
    "so what was the deal",
    "Sorry I cant help I am from Mass.!",
    "stop making fun of me..."
  ],
  t: ["To Kill a Mockingbird by Harper Lee...?"],
  u: ["Uhhhhh..... Dude! This 'aint your cell phone!"],
  v: [
    "very depressed a poem",
    "VERY POPULAR Techno Song?? HELP!!!",
    "Vaseline or Bengay- Slug question?",
  ],
  w: [
    "why are we aware that we're dreaming",
    "why are taxes so high in canada",
    "what are theese things on my rear end",
    "when i urinate why does it spray everywhere",
    "wisdom teeth taken out tomorrow ok",
    "women only please",
    "wow i think i am really losin it",
    "What took so long, Oprah?",
  ],
  x: ["xpect words that shows me ma girl love me?"],
  y: ["yes, I fall in love with the women that have blond hair with 3 inches of black roots, a nice muffin top and a dynamite camel toe ♥ I just melt ♥",
"ystrdy ma bst frnd ho is a gl(nt ma gf) tld me dat she likes a boy"],
  z: ["ziplining in the amazon?"],
};

export default yahooData;
